# p1

In [2]:
import pandas as pd


employees_large = pd.read_csv('employees_large.csv')


average_salary = employees_large.groupby('Department')['Salary'].mean()

highest_avg_salary_department = average_salary.idxmax()

print("Average Salary per Department:\n", average_salary)
print("\nDepartment with Highest Average Salary:", highest_avg_salary_department)


Average Salary per Department:
 Department
Engineering    125000.0
Finance         78000.0
HR              68000.0
IT              57750.0
Marketing       43750.0
Name: Salary, dtype: float64

Department with Highest Average Salary: Engineering


# p2

In [4]:

df_sales = pd.read_csv('sales_large.csv')

total_sales = df_sales.groupby(['Region', 'Product'])['Sales'].sum()

highest_selling_product = df_sales.groupby('Product')['Sales'].sum().idxmax()

print("Total Sales per Product per Region:\n", total_sales)
print("\nProduct with Highest Total Sales:", highest_selling_product)


Total Sales per Product per Region:
 Region   Product
Central  Apples      9000
         Oranges     8000
East     Apples      5000
         Bananas     8500
         Oranges    13900
North    Apples      7200
         Bananas     9000
         Oranges     4900
South    Apples     12900
         Bananas     5100
         Oranges     3000
West     Apples     18900
         Bananas    14700
         Oranges     7500
Name: Sales, dtype: int64

Product with Highest Total Sales: Apples


# p3

In [7]:
import numpy as np

A = np.array([[2, 4, 6], [1, 3, 5], [7, 9, 11]])
B = np.array([[8, 5, 2], [7, 4, 1], [6, 3, 0]])

sum_matrix = A + B

elementwise_product = A * B

matrix_product = np.dot(A, B)

determinant_of_A = np.linalg.det(A)

print("Sum of A and B:\n", sum_matrix)
print("\nElement-wise Product:\n", elementwise_product)
print("\nMatrix Product:\n", matrix_product)
print("\nDeterminant of A:", determinant_of_A)


Sum of A and B:
 [[10  9  8]
 [ 8  7  6]
 [13 12 11]]

Element-wise Product:
 [[16 20 12]
 [ 7 12  5]
 [42 27  0]]

Matrix Product:
 [[ 80  44   8]
 [ 59  32   5]
 [185 104  23]]

Determinant of A: 0.0


# p4

In [12]:
random_data = np.random.uniform(0, 1, 10000)

mean_value = np.mean(random_data)
median_value = np.median(random_data)
std_dev = np.std(random_data)

min_value = np.min(random_data)
max_value = np.max(random_data)

count_in_range = np.sum(random_data > mean_value)

normalized_df = (random_data - mean_value) / (max_value - min_value)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_dev)
print("Min Value:", min_value)
print("Max Value:", max_value)
print("Count of values greater than the mean:", count_in_range)

print("Normalized Data", normalized_df)



Mean: 0.5028830126912106
Median: 0.5066144011034832
Standard Deviation: 0.2895523981790172
Min Value: 0.00017479802638153963
Max Value: 0.9999758395305235
Count of values greater than the mean: 5032
Normalized Data [ 0.3067622  -0.14332668 -0.25689241 ... -0.10005543 -0.44874688
 -0.4181624 ]


# p5

In [13]:

temperatures = [28, 32, 35, 31, 29, 30, 33, 36, 27, 25, 34, 30, 29, 37, 38, 26, 31, 35,
33, 32, 36, 34, 29, 28, 27, 35, 32, 30, 31, 33]

high_temperatures = [temp for temp in temperatures if temp > 30]


categorized_temps = [(temp, "Hot" if temp > 35 else "Warm" if temp > 30 else "Cool") for temp in temperatures]


avg_temp = sum(temperatures) / len(temperatures)
temp_differences = [temp - avg_temp for temp in temperatures]

print("Temperatures above 30°C:", high_temperatures)
print("\nCategorized Temperatures:", categorized_temps)
print("\nTemperature Differences from Average:", temp_differences)


Temperatures above 30°C: [32, 35, 31, 33, 36, 34, 37, 38, 31, 35, 33, 32, 36, 34, 35, 32, 31, 33]

Categorized Temperatures: [(28, 'Cool'), (32, 'Warm'), (35, 'Warm'), (31, 'Warm'), (29, 'Cool'), (30, 'Cool'), (33, 'Warm'), (36, 'Hot'), (27, 'Cool'), (25, 'Cool'), (34, 'Warm'), (30, 'Cool'), (29, 'Cool'), (37, 'Hot'), (38, 'Hot'), (26, 'Cool'), (31, 'Warm'), (35, 'Warm'), (33, 'Warm'), (32, 'Warm'), (36, 'Hot'), (34, 'Warm'), (29, 'Cool'), (28, 'Cool'), (27, 'Cool'), (35, 'Warm'), (32, 'Warm'), (30, 'Cool'), (31, 'Warm'), (33, 'Warm')]

Temperature Differences from Average: [-3.533333333333335, 0.466666666666665, 3.466666666666665, -0.533333333333335, -2.533333333333335, -1.533333333333335, 1.466666666666665, 4.466666666666665, -4.533333333333335, -6.533333333333335, 2.466666666666665, -1.533333333333335, -2.533333333333335, 5.466666666666665, 6.466666666666665, -5.533333333333335, -0.533333333333335, 3.466666666666665, 1.466666666666665, 0.466666666666665, 4.466666666666665, 2.4666666